# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(max_length=30)),
                ('question_2', models.CharField(max_length=30)),
            ],
        ),
    ]
